// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ziphpzktmojzxyvdtamm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InppcGhwemt0bW9qenh5dmR0YW1tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3ODA3MTgsImV4cCI6MjA2NjM1NjcxOH0.tTl1lW1qx_9VJN0PZV8vUFvKkKlpJZ88vGiF_VylV-A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);